$(document).ready(function(){
    $(".bestseller .owl-carousel").owlCarousel({
        loop:true,
        nav:true,
        dots:true,
        margin:0,
        responsiveClass:true,
        dots:true,
        responsive:{
            0:{
                 items:2,
                 nav:true,
                 button:true
             },
             600:{
                 items:3,
                 nav:true,
                 button:true
             },
             1000:{
                 items:5,
                 nav:true,
                 loop:true,
                 button:true
             }
        }
    })

})